More Whitesands Ruins
Whitesands-Bot/WaspStation-1.0 pull request #17
Opened 2021-01-10 22:16 UTC by Maldaris

## About The Pull Request

Adds three variants of Survivor simple mobs, which wear the suit/guns created by 1GlitchyCent. 
Adds Survivor corpse spawners, a basic loot table, and loot spawners

Adds a "camp" system, which associates all mobs in the `map_template` definition with each-other using a randomized faction ID. Opens up further customizations in the future for this subset of ruins.

Adds the following camps:
* Survivor Camp
* Hunter Camp
* Gunslinger Camp
* Survivor Adobe Camp

## Why It's Good For The Game

Content!

## Changelog
:cl:
add: "Camp" system, which associates mobs within the camp with each other using a unique faction ID
add: Whitesands Camps & simple_mobs
/:cl:

2021-01-10 23:27 UTC, MarkSuckerberg requested changes
commit if you need em, don't if you've got plans for the code

2021-01-10 23:27 UTC, MarkSuckerberg commented on code/controllers/subsystem/mapping.dm
> +		seedRuins(sand_camps, CONFIG_GET(number/whitesands_budget), list(/area/whitesands/surface/outdoors/explored), sand_camps_templates)
```suggestion
		seedRuins(sand_camps, CONFIG_GET(number/whitesands_budget), list(/area/whitesands/surface/outdoors/explored), sand_camps_templates)
```

2021-01-10 23:27 UTC, MarkSuckerberg commented on code/__DEFINES/maps.dm
> +	ZTRAIT_SAND_CAMPS = TRUE, \
```suggestion
```

2021-01-10 23:27 UTC, MarkSuckerberg commented on code/__DEFINES/maps.dm
> +#define ZTRAIT_SAND_CAMPS "Sand Camps" // WS Edit - Whitesands - Specifically used for non-ruin spawns, like mob camps/fauna nests
```suggestion
```

2021-01-10 23:27 UTC, MarkSuckerberg commented on code/modules/mapping/ruins.dm
> +				// WS Edit End - Whitesands Camp Ruins
```suggestion

				placed_turf = current_pick.try_to_place(target_z,whitelist,forced_turf)
```

2021-01-11 00:25 UTC, MarkSuckerberg commented on code/datums/map_config.dm
> +GLOBAL_LIST_INIT(mining_maps, list("lavaland" = 0, "icemoon" = 0, "whitesands" = 1, "random" = 0))
?

2021-01-11 00:44 UTC, MarkSuckerberg approved these changes

2021-01-11 00:44 UTC, MarkSuckerberg commented
would still like clarification of change before merge

2021-01-11 02:38 UTC, Maldaris commented on code/datums/map_config.dm
> +GLOBAL_LIST_INIT(mining_maps, list("lavaland" = 0, "icemoon" = 0, "whitesands" = 1, "random" = 0))
whoops, debug code getting into main

2021-01-11 02:40 UTC, Maldaris commented on code/datums/map_config.dm
> +GLOBAL_LIST_INIT(mining_maps, list("lavaland" = 0, "icemoon" = 0, "whitesands" = 1, "random" = 0))
fixed

2021-01-11 02:42 UTC, merged